'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, Flag, Gauge, Heart, MapPin, Pause, Play, RotateCcw, Route, ShieldCheck, Sun, TriangleAlert, Volume2, VolumeX, Wrench } from 'lucide-react';
import styles from './cukur-rallisi.module.css';
import { DrivingSound } from './sound';
import { fresh, move, render, stageIndex, stages, step, type GameState } from './game';

export default function CukurRallisi(){
 const canvas=useRef<HTMLCanvasElement>(null);const game=useRef(fresh());const [ui,setUi]=useState<GameState>(fresh());const [muted,setMuted]=useState(false);const [best,setBest]=useState(0);const bestRef=useRef(0);const touch=useRef(0);const audio=useRef<DrivingSound|null>(null);const mutedRef=useRef(false);
 const [audioState,setAudioState]=useState('ready');const [audioLevel,setAudioLevel]=useState(0);const [updateAvailable,setUpdateAvailable]=useState(false);
 const snapshot=useCallback(()=>setUi({...game.current,objects:[...game.current.objects]}),[]);
 const unlockSound=useCallback(()=>{try{if(!audio.current)audio.current=new DrivingSound();audio.current.setMuted(mutedRef.current);audio.current.resume();}catch{setMuted(true);mutedRef.current=true;}},[]);
 const toggleSound=()=>{const playing=audio.current?.status().state==='running'&&!mutedRef.current;mutedRef.current=playing;setMuted(playing);if(!playing){unlockSound();audio.current?.effect('start');}else audio.current?.setMuted(true);};
 const start=()=>{game.current={...fresh(),status:'playing'};unlockSound();audio.current?.effect('start');snapshot();};
 const pause=useCallback(()=>{const s=game.current;if(s.status==='playing'||s.status==='paused'){s.status=s.status==='playing'?'paused':'playing';s.brake=false;if(s.status==='playing')unlockSound();else audio.current?.quiet();snapshot();}},[snapshot,unlockSound]);
 const steer=useCallback((d:number)=>{move(game.current,d);},[]);
 const brake=useCallback((b:boolean)=>{game.current.brake=b;},[]);
 useEffect(()=>{const check=()=>{void fetch('/oyunlar/cukur-rallisi/build.json',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(v=>{if(v&&typeof v==='object'&&'release' in v&&typeof v.release==='string'&&v.release!=='ugavole-2026-09-06.1')setUpdateAvailable(true);}).catch(()=>{});};const timer=setInterval(check,45000);window.addEventListener('focus',check);return()=>{clearInterval(timer);window.removeEventListener('focus',check);};},[]);
 useEffect(()=>{
   try{const saved=Number(localStorage.getItem('cukur-best')||0);if(Number.isFinite(saved)){bestRef.current=saved;}}catch{}
   const bg=new Image();bg.src='/oyunlar/cukur-rallisi/landscape.png';const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;
   let width=1000,height=650,last=0,raf=0,uiTime=0;
   const resize=()=>{const rect=c.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(2,window.devicePixelRatio||1);c.width=width*dpr;c.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);};
   const observer=new ResizeObserver(resize);observer.observe(c);resize();
   const frame=(t:number)=>{const dt=Math.min(.04,(t-last)/1000||0);last=t;const s=game.current;const hp=s.health,points=s.score,checks=s.checkpoints;const old=s.status;step(s,dt);audio.current?.update(s);if(s.health<hp)audio.current?.effect('hit');else if(s.checkpoints>checks)audio.current?.effect('checkpoint');else if(s.score-points===75)audio.current?.effect('repair');if(old==='playing'&&s.status==='won')audio.current?.effect('win');if(old==='playing'&&s.status==='over')audio.current?.effect('lose');
     if(old==='playing'&&(s.status==='over'||s.status==='won')){const score=Math.floor(s.score+s.distance*100);if(score>bestRef.current){bestRef.current=score;setBest(score);try{localStorage.setItem('cukur-best',String(score));}catch{}}}
     render(ctx,width,height,s,bg,t/1000);if(t-uiTime>90){uiTime=t;setBest(bestRef.current);const sound=audio.current?.status();setAudioState(sound?.state||'ready');setAudioLevel(sound?.level||0);snapshot();}raf=requestAnimationFrame(frame);
   };raf=requestAnimationFrame(frame);
   const keydown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLElement&&['INPUT','TEXTAREA'].includes(e.target.tagName))return;
     if(['ArrowLeft','ArrowRight','ArrowDown',' ','a','d','s','p','Escape'].includes(e.key)){
       if((e.target instanceof HTMLButtonElement)&&e.key===' ')return;e.preventDefault();
       if(e.key==='ArrowDown'||e.key===' '||e.key==='s')brake(true);
       if(e.repeat)return;if(e.key==='ArrowLeft'||e.key==='a')steer(-1);if(e.key==='ArrowRight'||e.key==='d')steer(1);if(e.key==='p'||e.key==='Escape')pause();
     }
   };const keyup=(e:KeyboardEvent)=>{if(['ArrowDown',' ','s'].includes(e.key))brake(false);};
   const hide=()=>{brake(false);audio.current?.quiet();if(game.current.status==='playing'){game.current.status='paused';snapshot();}};
   window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('blur',hide);document.addEventListener('visibilitychange',hide);
   return()=>{cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('blur',hide);document.removeEventListener('visibilitychange',hide);audio.current?.close();audio.current=null;};
 },[pause,steer,brake,snapshot]);
 const active=ui.status==='playing';const ended=ui.status==='over'||ui.status==='won';const stage=stageIndex(ui.distance);const police=ui.objects.some(o=>o.type==='police'&&!o.done&&o.z<.8);const score=Math.floor(ui.score+ui.distance*100);
 return <div id="cukur-rallisi" className={styles.root}>
   <header className="topbar"><a href="#cukur-rallisi" className="brand" aria-label="Çukur Rallisi"><span className="brand-mark"><Route size={24}/></span><span>ÇUKUR<span className="brand-light"> RALLİSİ</span><small>KUZEY KIBRIS YOL MACERASI</small></span></a><div className="header-route"><span>GİRNE</span><span className="route-dashes">······ <ArrowRight size={17}/> ······</span><span>LEFKOŞA</span></div><div className="header-right"><span className="weather"><Sun size={18}/> Hava güzel. Yol, tartışılır.</span><button className="icon-button sound" data-audio-state={audioState} data-audio-level={audioLevel.toFixed(5)} aria-label={audioState==='running'&&!muted?'Sesi kapat':'Sesi aç ve dene'} aria-pressed={audioState==='running'&&!muted} onClick={toggleSound}>{muted?<VolumeX size={20}/>:<Volume2 size={20}/>}<span>{muted?'Ses kapalı':audioState==='running'?(audioLevel>.0001?'Ses çalıyor':'Ses açık'):'Sesi aç'}</span></button></div></header>
   {updateAvailable&&<div className="update-notice" role="status">Oyunun yeni sürümü hazır.<button onClick={()=>window.location.reload()}>Güncelle ve yeniden başla</button></div>}
   <section className={`game-shell ${active?'is-playing':''}`} aria-label="Çukur Rallisi oyun alanı">
    <canvas ref={canvas} aria-label="Girne Lefkoşa yolunda üç şeritli sürüş oyunu" onTouchStart={e=>{touch.current=e.touches[0].clientX;}} onTouchEnd={e=>{const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>25)steer(d>0?1:-1);}}/>
    <div className="hud"><div className="location-chip"><span className="live-dot"/><div><small>ŞU AN BURADASIN</small><strong>{stages[stage]}</strong></div></div><div className="hud-right"><div className="score"><small>PUAN</small><strong>{score.toLocaleString('tr-TR').padStart(5,'0')}</strong></div><div className="health" aria-label={`${ui.health} can kaldı`}><small>ARACIN KEYFİ</small><div>{[0,1,2].map(n=><Heart key={n} size={21} fill={n<ui.health?'#e6b342':'transparent'} color={n<ui.health?'#e6b342':'#73837a'}/>)}</div></div><button className="icon-button pause" aria-label={ui.status==='paused'?'Devam et':'Duraklat'} disabled={ui.status==='ready'||ended} onClick={pause}>{ui.status==='paused'?<Play size={19}/>:<Pause size={19}/>}</button></div></div>
    {ui.status==='ready'&&<div className="start-panel"><div className="eyebrow"><span/> 3 ŞERİT. BOL SÜRPRİZ.</div><h2 className="game-title">Manzara güzel.<br/>Yola <em>dikkat.</em></h2><p>Girne’den Lefkoşa’ya küçük bir yolculuk.<br className="desktop-br"/> Çukurlara rağmen, keyfin yerinde kalsın.</p><div className="start-features"><span><TriangleAlert size={17}/> Çukurları atlat</span><span><ShieldCheck size={17}/> Çevirmede yavaşla</span><span><Wrench size={17}/> Aracını koru</span></div><button className="start-button" onClick={start}>YOLA ÇIK <ArrowUpRight size={23}/></button><div className="sound-note"><Volume2 size={13}/> Motoru duy, yolu hisset.</div><div className="start-bottom"><span><kbd>←</kbd> <kbd>→</kbd> şerit değiştir</span><span><kbd>BOŞLUK</kbd> fren</span></div>{best>0&&<div className="best">Kişisel rekorun · {best.toLocaleString('tr-TR')} puan</div>}</div>}
    {ui.status==='paused'&&<div className="shade"><div className="result-panel"><span className="result-icon"><Pause/></span><div className="eyebrow">KISA BİR MOLA</div><h2>Bir nefes al.</h2><p>Çukurlar bir yere gitmiyor.<br/>Hazır olunca kaldığın yerden devam et.</p><button className="start-button" onClick={pause}>DEVAM ET <Play size={20}/></button><button className="text-button" onClick={start}><RotateCcw size={16}/> Baştan başla</button></div></div>}
    {ended&&<div className="shade"><div className="result-panel"><span className="result-icon">{ui.status==='won'?<Flag/>:<Wrench/>}</span><div className="eyebrow">{ui.status==='won'?'LEFKOŞA’YA HOŞ GELDİN':'SANAYİ MOLASI'}</div><h2>{ui.status==='won'?'Yol bitti. Tebrikler!':'Yol 1, amortisör 0.'}</h2><p>{ui.status==='won'?'Bu yolculuğun en güzel yanı, varabilmek.':'Araba pes etti. Sen etme.'}</p><strong className="result-score">{score.toLocaleString('tr-TR')} <small>PUAN</small></strong><div className="result-stats"><span><b>{ui.distance.toFixed(1)}</b> km yol</span><span><b>{ui.dodged}</b> engel aşıldı</span><span><b>{ui.checkpoints}</b> güvenli kontrol</span></div><p className="result-message">Gerçek hayatta iyi bir yol,<br/>reflekslerinden daha çok şey kurtarır.</p><button className="start-button" onClick={start}>BİR TUR DAHA <RotateCcw size={20}/></button></div></div>}
    {active&&police&&<div className={`police-alert ${ui.speed<=35?'safe':''}`} role="status"><ShieldCheck size={21}/><span>{ui.speed<=35?'Hızın uygun. Böyle devam!':'Polis kontrolü! Frene basılı tut.'}<small>35 km/sa veya altıyla geç</small></span></div>}
    {active&&ui.messageTime>0&&<div className="game-message" role="status">{ui.message}</div>}
    <div className="scene-bottom"><span className="edition"><span/> ADA YOLLARI · BÖLÜM 01</span><div className={`speedometer ${ui.brake?'braking':''}`}><Gauge size={21}/><strong>{Math.round(ui.speed)}</strong><span>KM/SA<small>{ui.brake?'FREN':'OTOMATİK GAZ'}</small></span></div></div>
   </section>
   <div className="journey"><div className="journey-title"><MapPin size={18}/><span>YOLCULUĞUN</span><strong>{ui.distance.toFixed(1)} <small>/ 30 km</small></strong></div><div className="route-track"><div className="track-line"><div style={{width:`${ui.distance/30*100}%`}}/></div>{['Girne','Boğaz','Gönyeli','Lefkoşa'].map((name,i)=><div className={`track-stop ${i<=stage?'passed':''}`} key={name}><span>{i===3?<Flag size={11}/>:null}</span><small>{name}</small></div>)}</div></div>
   <div className="controls-row"><div className="controls"><button aria-label="Sola geç" onClick={()=>steer(-1)} disabled={!active}><ArrowLeft size={21}/></button><button aria-label="Sağa geç" onClick={()=>steer(1)} disabled={!active}><ArrowRight size={21}/></button><span>Şerit değiştir</span><button className="brake-button" disabled={!active} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);brake(true);}} onPointerUp={()=>brake(false)} onPointerCancel={()=>brake(false)} onLostPointerCapture={()=>brake(false)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();brake(true);}}} onKeyUp={()=>brake(false)}>FREN</button><span>Basılı tut</span></div><p><span className="green-dot"/> Biraz oyun, biraz memleket meselesi.</p></div>
   <footer data-release="ugavole-2026-09-06.1"><span>Çukurları oyunda atlatıyoruz. Gerçekte çözülmesini istiyoruz.</span><span>Güzergâhtan esinlenildi; mesafe, üç şerit ve olaylar oyunlaştırıldı. <a href="https://bub.gov.ct.tr/DA%C4%B0RE-VE-KURUMLAR/G%C4%B0RNE-L%C4%B0MAN-BA%C5%9EKANLI%C4%9EI/lefko%C5%9Fa-g%C4%B0rne-yolu-%C4%B0le-lefko%C5%9Fa-kuzey-199evre-yolunun-kes%C4%B0%C5%9Ft%C4%B0%C4%9F%C4%B0-noktada-%C4%B0n%C5%9Fa-ed%C4%B0lecek-olan-yonca-kav%C5%9Fa%C4%9Fin-yapim-199ali%C5%9Fmalari-ba%C5%9Fliyor" target="_blank" rel="noreferrer">Güzergâh kaynağı ↗</a></span></footer>
 </div>;
}
